# Generated by Django 2.2.3 on 2019-07-25 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('username', models.CharField(blank=True, default='', max_length=100)),
                ('linenos', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceUserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=100)),
                ('firstname', models.CharField(default='', max_length=100)),
                ('lastname', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('registrationdate', models.DateTimeField()),
                ('image', models.URLField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='UserworkDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, default='', max_length=100)),
                ('role', models.CharField(blank=True, default='', max_length=100)),
                ('insuranceuserprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing_apis.InsuranceUserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='UserbankDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(blank=True, default='', max_length=100)),
                ('account_name', models.CharField(blank=True, default='', max_length=100)),
                ('account_number', models.IntegerField(blank=True, default=0)),
                ('bvn', models.IntegerField(blank=True, default=0)),
                ('phone_number', models.IntegerField(blank=True, default=0)),
                ('insuranceuserprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing_apis.InsuranceUserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='MotorInsurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_maintenance', models.CharField(blank=True, default='', max_length=100)),
                ('chassis_number', models.CharField(blank=True, default='', max_length=100)),
                ('cost_price', models.IntegerField(blank=True, default=0)),
                ('date_of_purchase', models.DateTimeField(auto_now_add=True)),
                ('engine_number', models.IntegerField(blank=True, default=0)),
                ('fuel_capacity', models.IntegerField(blank=True, default=0)),
                ('mileage', models.IntegerField(blank=True, default=0)),
                ('car_model', models.CharField(blank=True, default='', max_length=100)),
                ('car_use', models.CharField(choices=[('General_cartage', 'General_cartage'), ('Goods_only', 'Goods_only'), ('Passangers_only', 'Passangers_only')], default='General_cartage', max_length=100)),
                ('purpose', models.CharField(blank=True, default='', max_length=100)),
                ('reg_no', models.IntegerField(blank=True, default=0)),
                ('vehicle_faults', models.TextField(blank=True, default='')),
                ('vehicle_types', models.CharField(blank=True, default='', max_length=100)),
                ('insuranceuserprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing_apis.InsuranceUserProfile')),
            ],
        ),
    ]
