# Generated by Django 2.2.3 on 2019-07-25 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing_apis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceuserprofile',
            name='token',
            field=models.CharField(default='4LJMTOH6R3ZT7TT01AC73R0MT0K5TWQ5BBK5V15X09X4L5NK', editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='insuranceuserprofile',
            name='registrationdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
