# Generated by Django 2.2.3 on 2019-07-25 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing_apis', '0002_auto_20190725_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuranceuserprofile',
            name='token',
            field=models.CharField(default='V8VEUAP10MJID4VQBCHBXHBATKHO0KGNIJ0MFUBO0F2Z6SR8', max_length=100),
        ),
    ]
