# Generated by Django 2.2.3 on 2019-07-25 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing_apis', '0003_auto_20190725_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuranceuserprofile',
            name='token',
            field=models.CharField(default='6P6JFHXIYCFA74MRV6N7EGJJQJHW7OG9NJVAYMNRBKXBWQ84', max_length=100),
        ),
    ]
