# Generated by Django 2.2 on 2019-07-26 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing_apis', '0004_auto_20190725_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuranceuserprofile',
            name='token',
            field=models.CharField(default='83D47PL5U8MLYM9KYG7Z2TXNWMNC4Y62CPX3H02FJUULWIU0', max_length=100),
        ),
    ]
