# Generated by Django 2.2 on 2019-07-26 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing_apis', '0005_auto_20190726_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuranceuserprofile',
            name='token',
            field=models.CharField(default='N3YCDXGZPK4PGYD3BYPFPB5O49IBOCDBPP0Q53L57U1ZR3Z7', max_length=100),
        ),
    ]
