# Generated by Django 2.2 on 2019-07-26 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing_apis', '0006_auto_20190726_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuranceuserprofile',
            name='token',
            field=models.CharField(default='RA11NEQVE1CD17CAMOZDR6D8JO1QMXPPLS4FSM8J67HB27V9', max_length=100),
        ),
    ]
