# Generated by Django 2.2.3 on 2019-07-25 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insuretech_apis', '0002_ainsuranceuserprofile_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ainsuranceuserprofile',
            name='token',
        ),
    ]
