# Generated by Django 2.2.3 on 2019-07-25 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuretech_apis', '0003_remove_ainsuranceuserprofile_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='ainsuranceuserprofile',
            name='token',
            field=models.CharField(default='4IGVTCY5382ARL9UE8ZPPUUMFOOE2TUPFUN04Y508C6T5SI6', max_length=100),
        ),
    ]
