# Generated by Django 2.2.3 on 2019-07-25 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuretech_apis', '0004_ainsuranceuserprofile_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ainsuranceuserprofile',
            name='token',
            field=models.CharField(default='7J7MI8UOC9UEV7FYNF2BFXE5U2YQHF5BCY89NPYG3DFE7K4C', editable=False, max_length=100),
        ),
    ]
