# Generated by Django 2.2.3 on 2019-07-25 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuretech_apis', '0007_auto_20190725_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ainsuranceuserprofile',
            name='token',
            field=models.CharField(default='O5WPZT7RCEI7B7RYAAS6W6HC9TZD4976NXUJ0WFS0VHS00B9', max_length=100),
        ),
    ]
