# Generated by Django 2.2 on 2019-07-26 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuretech_apis', '0008_auto_20190725_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ainsuranceuserprofile',
            name='token',
            field=models.CharField(default='TZL5N6A7DWS0BJJLMF2GF5TZ7MFHB9ZF9VQGFG92BNOX8J60', max_length=100),
        ),
    ]
