# Generated by Django 2.2 on 2019-07-26 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuretech_apis', '0009_auto_20190726_0723'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_type', models.CharField(choices=[('general', 'General'), ('auto', 'Auto'), ('life', 'Life'), ('health', 'Health')], default='general', max_length=50)),
                ('tip', models.TextField()),
            ],
            options={
                'ordering': ('insurance_type',),
            },
        ),
        migrations.AlterField(
            model_name='ainsuranceuserprofile',
            name='token',
            field=models.CharField(default='5IM6F4OQEL0VL7VDSAQE15XLLWGJNQQAK0CCYHGGPKC26TK7', max_length=100),
        ),
    ]
