# Generated by Django 2.2 on 2019-07-26 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuretech_apis', '0010_auto_20190726_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ainsuranceuserprofile',
            name='token',
            field=models.CharField(default='FBMXV31PUWJEADC2ZPDLEZNULKJUPRTFJLW6KQCV5Z4OXSIV', max_length=100),
        ),
    ]
